# conda env create --file environment.yml
name: data_science_platzi_projects
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  -pandas
  -os
  - jupyter
  - jupyterlab
  - pathlib
  - pip
  - pyprojroot
  - python=3.7
  - pip:
    - pyhere
    